package:
  name: pystache
  version: "0.5.4"

source:
  fn: pystache-0.5.4.tar.gz
  url: https://pypi.python.org/packages/d6/fd/eb8c212053addd941cc90baac307c00ac246ac3fce7166b86434c6eae963/pystache-0.5.4.tar.gz
  md5: 485885e67a0f6411d5252e69b20a35ca
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pystache = pystache:main
    #
    # Would create an entry point called pystache that calls pystache.main()

    - pystache=pystache.commands.render:main
    - pystache-test=pystache.commands.test:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - pystache
    - pystache.commands


about:
  home: http://github.com/defunkt/pystache
  license: MIT License
  summary: 'Mustache for Python'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
