package:
  name: flask-compress
  version: "1.3.0"

source:
  fn: Flask-Compress-1.3.0.tar.gz
  url: https://pypi.python.org/packages/4d/ce/44564d794ff7342ba376a92c88f8bb07f604d5d30f506bcde2834311eda8/Flask-Compress-1.3.0.tar.gz
  md5: fe3d9b75793699ceec279d37104c1a9c
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flask-compress = flask-compress:main
    #
    # Would create an entry point called flask-compress that calls flask-compress.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - flask

  run:
    - python
    - flask

# test:
  # Python imports
  # imports:

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/wichitacode/flask-compress
  license: MIT License
  summary: 'Compress responses in your Flask app with gzip.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
