package:
  name: simple-settings
  version: "0.9.0conf2"

source:
  fn: 0.9.0conf2.tar.gz
  url: https://github.com/zegami/simple-settings/archive/0.9.0conf2.tar.gz


requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - simple_settings
    - simple_settings.dynamic_settings
    - simple_settings.strategies

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/zegami/simple-settings
  license: MIT License
  summary: 'A simple way to manage your project settings'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
