package:
    name: nginx
    version: 1.11.4

source:
    fn: nginx-1.11.4.tar.gz
    url: https://nginx.org/download/nginx-1.11.4.tar.gz

    patches:
       - configure.patch

build:
    number: 5
    no_link: etc/*
    detect_binary_files_with_prefix: true

requirements:
    build:
        - openssl
        - zlib
        - pcre

    run:
        - openssl
        - zlib
        - pcre

about:
    home: http://www.nginx.org
    license: 2-clause BSD-like license

